"""Ingest Fathom transcripts batch 15 (recordings 589120244, 580818395, 589061130)."""
import asyncio
import sys
import uuid

sys.path.insert(0, ".")
from dotenv import load_dotenv
load_dotenv()

from app.core.database import get_session_factory
from app.core.config import get_settings
from app.services.ingestion.pipeline import IngestionPipeline
from app.services.ingestion.embedder import Embedder

USER_ID = uuid.UUID("889ff4f4-b782-4e9f-bfb1-e310ae132827")

TRANSCRIPTS = [
    {
        "source_id": "589120244",
        "date": "2026-02-23",
        "title": "Reunion de Liderazgo Flock — Proyectos, I+D, RRHH e Industria 4.0",
        "content": (
            "Meeting: Reunion de Liderazgo Flock — Proyectos Operativos, I+D, RRHH e Industria 4.0\n"
            "Date: 2026-02-23\n"
            "Participants: Mariano Ortega, Federico Valentino Lacoste, Naiara Acosta Najmanovich\n\n"
            "Contexto: Reunion de liderazgo de Flock. Se revisan clientes activos, estado del "
            "equipo de I+D, recursos humanos y la vertical de Industria 4.0.\n\n"
            "1. Cliente Vista — Computer Vision Deteccion de Derrames\n"
            "El cliente (contacto Manuel) cuestiono el uso de camaras OLED; ya tiene camaras Axis "
            "de USD 1.500. Resistencia a cambiar camaras. Acuerdo: para instalaciones nuevas "
            "se pondran camaras duales. El viernes se definen proveedores.\n"
            "Requisitos del cliente: (a) propuesta integral POC+MVP con costos de rollout, "
            "(b) hardware de borde (sin nube, por compliance de seguridad). El MVP es pago.\n"
            "El caso de negocio debe compararse contra el costo de la cuadrilla de inspeccion "
            "visual humana (costo que el cliente no tiene contabilizado hoy).\n"
            "Preocupacion interna: el interlocutor Mariano no recordaba lo planteado en "
            "reunion anterior. Postura: ir con cautela.\n\n"
            "2. Cliente Metrogas\n"
            "Federico tuvo reunion; el asistente esperado era un director pero fue solo una persona. "
            "Metrogas no tiene desarrollo interno (todo con consultoras SAP y Salesforce).\n"
            "Intereses detectados: (a) Cognify (plataforma de formacion con IA) — proxima reunion "
            "con RRHH; (b) datos y governance — tienen data lake creado pero sin governance "
            "en Power Apps; (c) Copilot Studio como evolucion de automatizaciones; (d) governance "
            "de IA — charla que deberia dar Mariano.\n\n"
            "3. Proyectos Operativos\n"
            "- Ituran: Charly aprendio Go de forma autonoma y performa bien. Oportunidad de "
            "ofrecer nuevas tecnologias (Computer Vision) dado el historial de proyectos caidos.\n"
            "- Nomadear (camionetas): termina la semana siguiente; posible upselling. Proyecto "
            "adelantado. Oportunidad de alianza con el cliente para que Flock entre a concesionarias.\n"
            "- Club Advanta (fidelizacion agricola): NPS 10/10. Contrato termina el 27 de marzo. "
            "Objetivo: upselling con equipo mas pequeno. Cuidado: Alfredo de Syngenta podria "
            "molestarse si Advanta se publica como cliente.\n"
            "- Scalter: Entregado. Nuevo proyecto arranca a mediados/fines de marzo "
            "(automatizacion a codigo, no con N8N por limitaciones de integracion con ERPs).\n"
            "- Toki (totem conversacional): En produccion. Issues: funciona peor a la tarde "
            "(memory leak — se reinicia cada manana). Prompt fue corregido (era agresivo para la venta). "
            "Decision pendiente: avatar con Eleven Labs solo (voz) vs. Simly (avatar completo).\n"
            "- ADA (aeropuertos): Buenas referencias del cliente, nuevo presupuesto. Constraint nuevo: "
            "cualquier evolucion debe integrarse con Salesforce.\n"
            "- Acciona Flow (automatizaciones N8N): Flujos en produccion. Trainees (los Juanes y Fer) "
            "generando automatizaciones. Mugi hace el control previo. Pendiente: crear catalogo "
            "de automatizaciones, metricas de ejecucion, y ambientes separados (staging vs. produccion). "
            "Mariano sugiere usar MCP de Claude conectado a N8N para validar calidad de flujos.\n\n"
            "4. I+D — Estado del Equipo\n"
            "- Marilyn se afianza como lider del equipo. Algunas dificultades con Denis y Mati Araujo.\n"
            "- Vision 360 v2: Luisina generando imagenes sinteticas termicas para modelo de "
            "deteccion de derrames. Equipo I+D enfocado en avanzar para el modelo de Vista.\n"
            "- Agora (entrevistas con IA): MVP funcional en proceso de cierre para equipo de Talento. "
            "Feature de deteccion de 'IA respondiendo entrevistas' siendo investigado. "
            "Presentacion a Belen y Guada pendiente.\n"
            "- Robotica: SLAM + Aruco + waypoints ya funcionan virtualmente. Demo presencial pendiente "
            "antes de las vacaciones de Mati Araujo. Para Vaca Muerta: detectar imagen del robot "
            "con YOLO y transmitirla en Vision 360.\n"
            "- Avatares: Avatar propio en Unity ya funciona con Eleven Labs (lip-sync, integracion "
            "con agente IA, deployable en web y celular). Investigando MetaHuman (Unreal Engine).\n"
            "- Cognify: Disponible para uso interno. Caso de uso: capacitacion de Project Managers para Acciona.\n\n"
            "5. IA Day / Digital Maturity Challenge (Acciona)\n"
            "Federico organizando evento de todo el dia en Acciona para medir madurez digital. "
            "Estructura: talleres de prompts, cruce de informacion, examen final. Primeros 3 puestos "
            "con premio. Fecha tentativa: mediados de abril. Oportunidad de vender este formato a "
            "otras empresas para posicionamiento.\n\n"
            "6. Herramientas y Tecnologia Interna\n"
            "- Claude preferido sobre ChatGPT para trabajo diario. Naiara va a contratar Claude "
            "con descuento via Ripio (50%). Limite de Opus 4.6 en suscripcion USD 20 se agota rapido.\n"
            "- Copilot Studio: util para busqueda dentro del tenant de Microsoft. Limitaciones de "
            "tamano de prompt en version 365; para saltarlas hay que ir a Azure (pay-per-token).\n"
            "- Fathom: Mariano ya no tiene resumenes Pro gratuitos. Federico usa transcripciones "
            "crudas con prompts propios en ChatGPT para evaluar entrevistas comerciales.\n"
            "- N8N: preferido sobre Copilot Studio para automatizaciones. Metricas disponibles "
            "en el dashboard.\n\n"
            "7. Recursos Humanos\n"
            "- Fer Arjona: Sin asignacion oficial paga. En Acciona Flow sin costo. En evaluacion "
            "(si negativa, entra a proceso de mejora de performance con posible desvinculacion).\n"
            "- Gazabe (Seba): Vuelve de Espana el viernes/sabado. Probable salida definitiva a "
            "Espana en abril. Sus condiciones de ingreso a Flock (posible area de Industria 4.0) "
            "se cierran la semana proxima.\n"
            "- Pepe: A partir de marzo no sigue. Empezó en otra empresa. Rol a cubrir: "
            "comercial/preventa con foco en Praia. Plan: contacto de Mariano de Penta (Matias) "
            "para deal de OpenKey.\n"
            "- Nuevo comercial: Ingresaria el 16 de marzo. Perfil tecnico orientado a venta "
            "con mockups. Segundo comercial adicional en busqueda.\n"
            "- Trainees (Juanes): Desde mediados de marzo, uno se forma en React y otro en Node. "
            "Debate: Mariano cuestiona si es necesario aprender codigo tradicional en la era de "
            "Claude Code; Naiara considera que una base les da mejor criterio.\n\n"
            "8. Industria 4.0 y Estructura Organizacional\n"
            "Pendiente definir donde queda Industria 4.0 (Seba + Pau) en el organigrama. "
            "Propuesta: tres espacios: (a) reunion de management cada 15 dias, (b) reunion "
            "comercial con Mati Gazzave y Agus, (c) espacio de sinergia con Flock completo.\n"
            "Para la proxima reunion con socios (abril): mostrar Industria 4.0 como parte de Flock, "
            "casos de uso con vision de negocio (caso Vista con ROI calculable), upselling de "
            "Advanta y Scalter, implementacion de IA en operaciones.\n\n"
            "9. OpenKey\n"
            "Deal gestionado por Pepe a traves de contacto Matias (conocido de Mariano de Penta). "
            "Estado: en pausa, se activaria en un mes. Mariano de Penta tomara el contacto "
            "con Matias para continuidad tras la salida de Pepe."
        ),
    },
    {
        "source_id": "580818395",
        "date": "2026-02-13",
        "title": "Reunion Estrategica Flock — Nuevo Modelo de Negocio, Perfiles Comerciales y Metricas",
        "content": (
            "Meeting: Reunion Estrategica Flock — Nuevo Modelo de Negocio, Perfiles Comerciales y Metricas\n"
            "Date: 2026-02-13\n"
            "Participants: Mariano Ortega, Santiago Samra, Naiara Acosta Najmanovich, "
            "Federico Valentino Lacoste\n\n"
            "Contexto: Reunion de socios/directivos de Flock. Temas: nuevo perfil de marketing, "
            "perfiles comerciales, nuevo modelo de negocio, metricas de la empresa y NPS de clientes.\n\n"
            "1. Perfil de Marketing (Nuevo Ingreso)\n"
            "Perfil cross que cubre Flock y Acciona. Reporta directamente a Federico (por su "
            "caracter transversal). Gus participara en la definicion estrategica.\n"
            "Candidata principal: Sofia (entrevistada por Naiara). Genera preocupacion por falta "
            "de respuesta a mails de confirmacion y cancelacion de reunion.\n"
            "El rol tiene cuatro patas: ventas de Flock, ventas de Acciona, marca empleadora de "
            "ambas empresas, y coordinacion de campanas de prospeccion. Fede considera que el foco "
            "mas importante es el inbound de Flock.\n"
            "Naiara propone que sea 'Flocker' (cultura y beneficios de Flock) dado el perfil de "
            "la candidata. Pendiente: cruzar opiniones entre Nai y Fede antes de avanzar.\n\n"
            "2. Perfiles Comerciales — Transicion de Mati a Espana y Nuevo Comercial Jorge\n"
            "Mati (Matias Loizaga / Gazabe):\n"
            "- Visa espanola aprobada. Se muda a Espana despues de volver del Mobile World Congress.\n"
            "- Foco principal: Espana. Vision: en 6 meses contrata un perfil mas junior en Espana.\n"
            "- Fede advierte que Espana lo va a absorber (datos CECI: empresas argentinas en Espana "
            "apenas mantuvieron clientes en 2025, ninguna crecio).\n"
            "- Acuerdo: Mati no debe desconectarse de Argentina (fuente de credenciales y casos "
            "para vender en Espana). Punto de revision: mitad de ano.\n"
            "Nuevo comercial — Jorge Asfow:\n"
            "- Perfil tecnico con experiencia vendiendo desarrollo de software.\n"
            "- Objetivo propuesto: USD 500.000 por Q. Fede lo acepta porque el candidato se siente "
            "comodo con esa cifra.\n"
            "- Estrategia de arranque: cross-selling dentro de Acciona (Flock ya es proveedor).\n"
            "- Modelo de comisiones no lineal (periodos semestrales, primer periodo con menor exigencia).\n"
            "- Seguimiento 100% dentro de Flock (no tercerizado).\n"
            "Lautaro (preventa):\n"
            "- Fede expresa preocupacion: lleva varios meses y no participo en ninguna reunion "
            "comercial externa con Mati.\n"
            "- Santi se lleva la accion: entender por que no esta sucediendo y planificar exposicion "
            "en reuniones con clientes.\n\n"
            "3. Nuevo Modelo de Negocio — Debate Estrategico (presentacion de Santiago Samra)\n"
            "Diagnostico: el modelo actual de venta por horas de desarrollo esta en declive. "
            "La IA acelera la comoditizacion del desarrollo, acorta proyectos y genera presion "
            "a la baja en precios.\n"
            "Propuesta central: dejar de vender horas y empezar a vender resultados / resolver "
            "problemas de negocio.\n"
            "Debate sobre fixed price con IA:\n"
            "- La IA no elimina la ambiguedad de alcance pero permite prototipar muy rapido.\n"
            "- El problema cultural del fixed price (presion, baja calidad, deadlines imposibles) persiste.\n"
            "- Naiara: el mercado puede no estar maduro para este modelo todavia.\n"
            "- Mariano: hay que reinventar un modelo hibrido — combinar proyectos cerrados con "
            "etapas agiles. Casos problematicos: Syngenta (30 personas definiendo requerimientos), "
            "Banco Industrial.\n"
            "Propuesta de modelo hibrido (Fede):\n"
            "- Etapa 1: captura de la idea, MVP/prototipo con IA, precio cerrado (Flock define el detalle).\n"
            "- Etapa 2: a partir del feedback del MVP, modelo de horas o hibrido.\n"
            "- Aplica para: startups, empresas sin area de sistemas definida, clientes que "
            "hablan desde el negocio (no desde IT).\n"
            "Cambio de buyer persona (conclusion estrategica):\n"
            "- Hoy Flock vende a areas de sistemas. El nuevo modelo requiere vender al negocio.\n"
            "- El negocio tiene mayor presupuesto, plantea problemas sin saber de tecnologia, "
            "quiere que le resuelvan el dolor.\n"
            "- Ejemplos: Vista Energy (deteccion de derrames), frigorifico (contar vacas con CV), Dreyfus.\n"
            "- Desafio: para vender al negocio hay que entender su industria (hoy Flock no tiene "
            "esa capacidad instalada).\n"
            "- Estrategia: ir a ferias de industria (ej. Oil & Gas) en lugar de ferias de tecnologia.\n"
            "Offering diferenciado:\n"
            "- Inmediato: actualizar el offering actual mostrando como Flock incorpora IA "
            "(reduccion de tiempos ~30%, herramientas, casos de exito).\n"
            "- Mediano plazo: propuesta disruptiva de precio por resultado/negocio.\n"
            "Migracion tecnologica con IA (propuesta de Fede):\n"
            "- Ofrecer migracion de plataformas legacy (Oracle Forms, .NET, COBOL) a modernas usando IA.\n"
            "- Referencia: Anthropic Claude Code incorporo soporte COBOL. Contexto: Federacion "
            "Patronal tiene Oracle Forms.\n"
            "- Prueba en curso: usar Claude Code Max para migrar Oracle Forms a store procedures.\n\n"
            "4. Metricas de Flock\n"
            "- Headcount: 79 personas (80 al dia siguiente).\n"
            "- Diversidad: subio positivamente.\n"
            "- Rotacion (attrition) 2025: 9,5% — considerado bajo. Acumulado 2026: 1,3%.\n"
            "- Headcount de estructura bajo como porcentaje de la masa total.\n"
            "- Antiguedad promedio: 34 meses — sube consistentemente.\n"
            "- Partners (contractors): 29% adicional (~25 personas), total gestionado real ~100.\n"
            "- Problema con contractors: algunos piden mas estabilidad y contratos mas largos.\n\n"
            "5. NPS y Satisfaccion de Clientes\n"
            "- Syngenta: NPS 6 en dos etapas consecutivas. Causas: cambio de perfil a mitad del "
            "proyecto; el decisor (Alfredo) no vio valor al Team Manager y el alcance final "
            "no era lo que queria. Error clave: no se documentaron ni comunicaron las decisiones "
            "de alcance al decisor. Plan: reunion con Alfredo para reconocer errores y abrir "
            "conversacion hacia futuro.\n"
            "- Metrogas: NPS 7 con CISAT 9-10. El contacto esta contento pero no se anima a "
            "recomendar porque solo tiene una persona de Flock asignada.\n"
            "- Scalter: NPS bajo por demoras en entrega (camara), pero al final valoraron el "
            "esfuerzo del equipo.\n\n"
            "6. Highlights de Clientes\n"
            "- Federacion Patronal: negociacion activa. Se incrementara el equipo (~4 personas mas). "
            "Contrato buscado por un ano. Prueba: migrar Oracle Forms con Claude Code Max en lugar "
            "de contratar 2 perfiles PL/SQL.\n"
            "- Cencosud: Bajaron a Basti (perfil de menor seniority) por presupuesto. Compras "
            "defendio a Flock como proveedor valioso.\n"
            "- Advanta: alta probabilidad de continuidad; backlog enorme.\n"
            "- City: nuevo perfil de Scrum Master ingresa.\n\n"
            "Accionables:\n"
            "- [Nai + Fede] Cruzar opiniones sobre Sofia (marketing) y tomar decision.\n"
            "- [Santi] Hablar con Mati sobre caso Syngenta/Alfredo; generar encuentro informal.\n"
            "- [Santi] Seguimiento del rol de Lautaro en preventa; entender por que no participa.\n"
            "- [Santi] Refinar PPT de nuevo modelo de negocio con lo discutido y presentar a socios.\n"
            "- [Fede] Actualizar offering actual mostrando incorporacion de IA.\n"
            "- [Naiara/Manu] Probar migracion de Oracle Forms con Claude Code Max en Federacion.\n"
            "- [Nai] Hablar sobre futuro de Advanta y Nomadear la semana siguiente."
        ),
    },
    {
        "source_id": "589061130",
        "date": "2026-02-20",
        "title": "POC Proden — Deteccion de Fugas y Derrames con Vision 360, Alcance y Propuesta",
        "content": (
            "Meeting: POC Proden — Deteccion de Fugas y Derrames con Vision 360, Alcance y Propuesta\n"
            "Date: 2026-02-20\n"
            "Participants: Sebastian Loizaga, Mariano Rivanera (Proden), Manuel Barros (Proden), "
            "Mariano Ortega, Paula Vejrup\n\n"
            "Contexto: Reunion para definir el alcance y estructura de la POC de Flock para "
            "Proden (empresa de oil & gas), sobre deteccion de fugas y derrames con Computer Vision.\n\n"
            "1. Instalacion Seleccionada — Bateria 3\n"
            "Se eligio la Bateria 3 (bateria barra planta de tratamiento) como instalacion para "
            "la POC: 8 camaras (4-5 en la parte de bateria, 3 en la planta de tratamiento).\n"
            "Bateria 4 descartada: es nueva y tiene solo una camara en un trailer.\n"
            "Problema de historico: no hay historial de derrames en Bateria 3 (los que ocurrieron "
            "estan en otra instalacion con camaras de seguridad patrimonial mal posicionadas). "
            "Ademas, el historico de camaras se borra cada 30 dias. El ultimo evento del 2025 "
            "(24-26 de diciembre) ya no esta disponible. Por tanto, no se puede usar historico "
            "para entrenar el modelo — hay que generar simulaciones.\n\n"
            "2. Estructura de la POC — 4 Etapas\n"
            "Etapa 1 — POC (Modelo):\n"
            "- Reemplazar 2 camaras de Bateria 3 por 2 camaras duales (optica + termica).\n"
            "- Generar imagenes sinteticas de derrames/fugas (en paralelo con la instalacion).\n"
            "- Realizar simulaciones reales en campo (en conjuncion con el equipo de Proden: "
            "identificar puntos de mayor probabilidad de ocurrencia, simular eventos de distintas "
            "intensidades, temperaturas y colorimetria).\n"
            "- Con los datos reales + sinteticos, entrenar el modelo de deteccion.\n"
            "- Timeline: ~1 mes desde que se reciben los videos de las camaras instaladas.\n"
            "- Foco: modelo, sin integracion real-time en esta etapa.\n"
            "- Costo: a cargo de Flock (POC gratuita para el cliente).\n"
            "Etapa 2 — MVP (Integracion Real-Time):\n"
            "- Conectar el modelo entrenado a stream en tiempo real de las mismas 2 camaras.\n"
            "- Integrar con la plataforma Vision 360 para visualizacion.\n"
            "- Implementar sistema de notificaciones (email, WhatsApp o mensajeria).\n"
            "- Costo: pago (a cotizar; se enviaran numeros de referencia al cliente).\n"
            "Etapa 3 — Rollout de la Instalacion: despliegue completo en Bateria 3.\n"
            "Etapa 4 — Despliegue Masivo: extension a otras instalaciones.\n"
            "Proden considera las Etapas 1 y 2 como su 'POC' completa; el resto es rollout.\n\n"
            "3. Debata sobre Camaras — Termicas vs. RGB\n"
            "Manuel Barros: Proden tiene 8 camaras Axis instaladas (solo opticas, ~USD 1.500/c), "
            "mas las referenciadas a USD 9.000-10.000 (termometricas) o USD 1.500-8.000 (termograficas). "
            "Duda: si el modelo se entrena con camaras termicas y el cliente tiene RGB, el modelo "
            "no funcionara con la infraestructura existente.\n"
            "Sebastian: la solucion con camaras duales (optica + termica) esta bien estudiada; los "
            "modelos de deteccion de derrames en el mundo generalmente necesitan las camaras duales "
            "para buena efectividad. Si las camaras duales que propone Flock cuestan ~USD 1.000, "
            "podrian ser competitivas vs. los USD 1.500 que ya paga Proden por las opticas.\n"
            "Mariano (Proden): si el modelo funciona bien, hacer un reemplaz podria ser viable "
            "dependiendo del costo-beneficio.\n"
            "Manuel: para instalaciones nuevas, si las duales son competitivas en precio, tiene "
            "sentido adoptarlas como estandar. Para las instalaciones con camaras ya instaladas "
            "(8 camaras en Bateria 3, ~40 en total en la empresa), el reemplazo es mas complejo.\n"
            "Mariano (Ortega/Flock): la evidencia mundial indica que para buena deteccion se "
            "necesitan las dos camaras. Con RGB solo es posible pero con menor efectividad.\n\n"
            "4. Infraestructura — Edge Computing\n"
            "Proden no puede usar nube por ciberseguridad (compliance, todo on-premises).\n"
            "Por tanto, el procesamiento de video y el modelo deben correr en hardware de borde.\n"
            "Mariano (Flock): el MVP puede hacer el procesamiento en edge (hardware local) o "
            "en la nube del cliente si tienen acuerdo. Dado que no pueden usar nube, se trabajara "
            "con hardware de borde. Esto debe incluirse en la propuesta.\n\n"
            "5. Timeline y Urgencia del Cliente\n"
            "Proden necesita tomar una decision esta semana (viernes). Motivo: nuevas instalaciones "
            "con camaras que arrancan desde mayo-junio 2026, y quieren tenerlas con el nuevo "
            "sistema de monitoreo desde el inicio (en lugar de sumar personal de inspeccion "
            "de forma tradicional).\n\n"
            "6. Costos de Rollout — Informacion Pendiente\n"
            "Manuel: necesita numeros de referencia para el rollout (no solo la POC) para "
            "poder cerrar el caso de negocio internamente. Si avanzaran con la POC y luego "
            "el rollout cuesta USD 3.000/mes/camara, habran perdido tiempo sin sentido.\n"
            "Modelo de precios solicitado: por grupo de camaras, fee por camara, fee anual, etc.\n"
            "Sebastian: enviara en breve la propuesta detallada con las etapas, tiempos y "
            "los numeros de referencia de la masificacion.\n\n"
            "Decisiones:\n"
            "- Instalacion de la POC: Bateria 3 con 2 camaras duales reemplazando las existentes.\n"
            "- Estructura aprobada: POC (etapa 1, ~1 mes post-instalacion) + MVP (etapa 2, real-time).\n"
            "- Procesamiento en borde (no nube).\n"
            "- Para instalaciones nuevas: adoptar camaras duales como estandar si el precio es "
            "competitivo.\n\n"
            "Accionables:\n"
            "- [Sebastian] Enviar propuesta detallada con estructura de etapas, tiempos y "
            "numeros de referencia de la masificacion esta semana.\n"
            "- [Flock] Incluir en la propuesta: hardware de borde para el MVP, modelo de precios "
            "de rollout (fee por camara o grupo, anual).\n"
            "- [Proden - Manuel/Mariano Rivanera] Evaluar la propuesta y comparar con otras "
            "ofertas. Decidir proveedor el viernes.\n"
            "- [Flock] Confirmar marca y modelo de camaras duales usadas para la POC "
            "(mencionado Axis como posible, pendiente de verificacion)."
        ),
    },
]


async def main() -> None:
    settings = get_settings()
    session_factory = get_session_factory()
    pipeline = IngestionPipeline(embedder=Embedder(api_key=settings.openai_api_key))

    async with session_factory() as db:
        for t in TRANSCRIPTS:
            print(f"Ingesting {t['source_id']} — {t['title']}...")
            result = await pipeline.ingest_raw(
                db=db,
                user_id=USER_ID,
                content=t["content"],
                source="fathom",
                source_id=t["source_id"],
                metadata={
                    "title": t["title"],
                    "date": t["date"],
                    "recording_url": f"https://fathom.video/calls/{t['source_id']}",
                },
            )
            print(f"  -> created={result.documents_created} updated={result.documents_updated}")
        await db.commit()

    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
