"""Ingest Fathom transcripts batch 19 (recordings 415734708, 396920438, 329520793, 312484523)."""
import asyncio
import sys
import uuid

sys.path.insert(0, ".")
from dotenv import load_dotenv
load_dotenv()

from app.core.database import get_session_factory
from app.core.config import get_settings
from app.services.ingestion.pipeline import IngestionPipeline
from app.services.ingestion.embedder import Embedder

USER_ID = uuid.UUID("889ff4f4-b782-4e9f-bfb1-e310ae132827")

TRANSCRIPTS = [
    {
        "source_id": "415734708",
        "date": "2025-09-18",
        "title": "Reunion estrategica Flock + Ipatagonia — Alianza comercial IA en LATAM y EE.UU.",
        "content": (
            "Meeting: Reunion estrategica Flock + Ipatagonia — Alianza comercial IA en LATAM y EE.UU.\n"
            "Date: 2025-09-18\n"
            "Participants: Mariano Ortega, Federico Valentino Lacoste, Matias Loizaga, German Pardo (Ipatagonia)\n\n"
            "Contexto: Primera reunion de acercamiento entre Flock/Acciona y German Pardo de Ipatagonia, "
            "consultora de transformacion digital fundada en 2011 (Argentina, con presencia en Florida, EE.UU.). "
            "El objetivo es explorar una alianza comercial para llevar soluciones de IA a clientes de Ipatagonia "
            "en LATAM y EE.UU.\n\n"
            "1. Perfil de Ipatagonia\n"
            "- Consultora fundada en 2011, especializada en transformacion digital: ingenieria de procesos, "
            "gestion del cambio, armado de RFPs/RFIs, analisis de propuestas.\n"
            "- Desde hace 3 anos sumaron equipo de BI y desarrollo a pedido de clientes como Arcos Dorados y NSR.\n"
            "- German reside en Weston, Florida, desde hace 4.5 anos; desarrollando mercado EE.UU.\n"
            "- Problema clave: sus clientes quieren IA pero no saben que ni por donde empezar. Ipatagonia "
            "no tiene el musculo de innovacion/AI internamente y no quiere desarrollarlo.\n"
            "- Casos de exito propios: IA con McDonald's/Arcos Dorados y Masters (200 locales mantenimiento "
            "de pisos, EE.UU.).\n\n"
            "2. Perfil de Flock/Acciona\n"
            "- Flock es la unidad de innovacion y desarrollo del grupo Acciona, liderada por Mariano.\n"
            "- Organizacion de ~500 personas.\n"
            "- Han dado charlas de IA a mas de 200 empresarios.\n"
            "- Proyectos en curso: totems conversacionales en Aeropuertos Argentina, marco de IA para Ingenta "
            "(agro) y Aeropuertos, automatizaciones, agentes, computer vision, aplicaciones multiagente.\n\n"
            "3. Problema Comun Identificado\n"
            "Los clientes de ambas partes quieren IA pero:\n"
            "- No saben que quieren ni por donde empezar.\n"
            "- Tienen licencias (ej. Microsoft Copilot) sin usar mas alla del chat basico.\n"
            "- Usan ChatGPT con informacion confidencial sin governance.\n"
            "- Necesitan un camino gradual de maduracion, no una entrega 'big bang'.\n"
            "Solo el 5% de empresas que trabajan con IA tienen algo en produccion (dato citado por Fede).\n\n"
            "4. Propuesta de Colaboracion Estrategica\n"
            "Ipatagonia aporta:\n"
            "- Relaciones comerciales y pipeline de clientes en LATAM y EE.UU.\n"
            "- Expertise en consultoria de procesos y gestion del cambio.\n"
            "Flock/Acciona aporta:\n"
            "- Capacidad tecnica de ejecucion: IA, computer vision, agentes, cloud.\n"
            "- Casos de exito demostrables.\n"
            "- Equipo de ~500 personas con capacidad de armar celulas agiles rapidamente (plug and play).\n"
            "- Verticales: Insurtech, Fintech, Oil & Gas, Agro.\n"
            "Modelo propuesto: alianza (denominada 'shame venture' por German) donde Ipatagonia hace el "
            "front comercial y Flock ejecuta. Se discutio presentarse como equipo integrado o con "
            "identidad transparente de cada parte.\n\n"
            "5. Pipeline de Oportunidades de Ipatagonia\n"
            "- Prevencion ART (Grupo Galeno): diagnostico por imagen, deteccion de posturas ergonometricas.\n"
            "- Empresa Colombia (textil): IA en produccion y procesos.\n"
            "- Empresa Paraguay (partes de automoviles): IA en abastecimiento/proyeccion.\n"
            "- Marval (y Farrel): estudio juridico mas grande de Argentina/LATAM. Reunion al dia siguiente.\n"
            "- Empresa Ecuador (importador bananas/agro/logistica): CV en empaquetado, logistica, "
            "forecast de produccion (todo en Excel actualmente).\n"
            "- Empresa Bolivia (manufactura): IA en produccion, abastecimiento, forecast de ventas.\n"
            "- Empresa Chile (salmonera, 2da mas grande del mundo): IA en produccion. Reunion 9 de octubre.\n"
            "- Colombia (conversacion previa con caso de exito Arcos Dorados): 3ra reunion activa.\n\n"
            "6. Casos de Exito de Flock Compartidos\n"
            "- Totem conversacional en aeropuertos y textiles.\n"
            "- Computer Vision — deteccion de fallas en tela (cámara detecta patron de falla y alerta).\n"
            "- Computer Vision — cadena de produccion industrial: cuenta unidades, actualiza ERP "
            "(baja stock MP, genera stock producto terminado), tablero de velocidad por operario.\n"
            "- Computer Vision — packaging: conteo de unidades por caja.\n"
            "- Marco de IA para Aeropuertos Argentina e Ingenta (agro).\n\n"
            "7. Diferencias Mercado EE.UU. vs. LATAM\n"
            "- EE.UU. exige certificaciones y compliance antes de evaluar funcionalidad.\n"
            "- Empresa Tier 1 en LATAM = Tier 3 en EE.UU. (McDonald's: 14.000 locales EE.UU. vs. 2.000 LATAM).\n"
            "- En EE.UU. Acciona/Flock llega principalmente como staffing, no proyectos de valor agregado.\n"
            "- Tendencia emergente: celulas agiles integradas al cliente vs. proyectos largos (1.5-2 años).\n\n"
            "Accionables:\n"
            "- [German] Preparar documento (2 paginas) con casos activos del pipeline para compartir a Flock.\n"
            "- [Fede/Mati] Compartir links de casos de exito y materiales de Flock con German.\n"
            "- [Ambos] Reunion de 'peloteo' para alinear modelo de colaboracion.\n"
            "- [Ambos] Definir storytelling de presentacion conjunta (que es cada uno, que aporta).\n"
            "- Objetivo: tener offering definido antes de la reunion del 9 de octubre (salmonera chilena) "
            "y de la reunion de la semana siguiente (empresa paraguaya).\n"
            "- Considerar landing page/brochure/demo especifico para la alianza."
        ),
    },
    {
        "source_id": "396920438",
        "date": "2025-09-01",
        "title": "Preparacion propuesta Vista Energy — Robot cuadrupedo, videoanalytics y totem",
        "content": (
            "Meeting: Preparacion propuesta Vista Energy — Robot cuadrupedo, videoanalytics y totem\n"
            "Date: 2025-09-01\n"
            "Participants: Gustavo Castro, Mariano Ortega, Sebastian Loizaga, Paula Vejrup, "
            "Federico Valentino Lacoste\n\n"
            "Contexto: Reunion interna de preparacion para la reunion comercial con Vista Energy "
            "(3era productora petrolera a nivel nacional en Argentina). Vista quiere implementar "
            "soluciones tecnologicas en modalidad fast-track para reducir dependencia de operadores "
            "humanos en plantas e instalaciones de pozos.\n\n"
            "1. Contexto Vista Energy\n"
            "Vista Energy es la tercera productora petrolera nacional de Argentina. Su gerente de "
            "innovacion es un ex-Chevron con quien el equipo ya tiene relacion de confianza. Vista "
            "habia consultado a otros proveedores: Nestor Rios (local) y Boston Analytics (EE.UU., "
            "soluciones cerradas y costosas). Diferencial de Flock: integracion inteligente, no solo hardware.\n"
            "Modelo de negocio: Vista compraria el robot; Flock haria la integracion, programacion "
            "y soporte continuo. Se descarto por ahora el modelo 'robot as a service' por falta de "
            "madurez interna.\n\n"
            "2. Tres Pilares de la Propuesta\n\n"
            "A. Robot Cuadrupedo (Unitree) — Alta prioridad para Vista, baja madurez interna\n"
            "Estado: El equipo compro un robot Unitree para investigacion, pero el proveedor Big Dipper "
            "envio por error un modelo superior (el doble o triple de valor). El robot correcto no fue "
            "entregado; Pablo gestiona el reemplazo (varios meses de plazo). El robot incorrecto no "
            "puede usarse (riesgo de invalidar garantia).\n"
            "Explorando: sistema operativo ROS (Robot Operating System) — estandar para todos los "
            "robots Unitree. Posibilidad de agregar placa NVIDIA Jetson como modulo externo.\n"
            "Casos de uso planificados para Vista:\n"
            "- Patrullaje autonomo por puntos predefinidos (A→B→C) con registro de datos.\n"
            "- Transmision en vivo de anomalias detectadas.\n"
            "- Alerta por sonidos anomalos.\n"
            "- Evacuacion automatica ante gases explosivos (robot se retira a zona segura).\n"
            "Limitaciones tecnicas:\n"
            "- Sin certificacion antiexplosivos: solo pueden operar en zonas perimetrales, no Clase 1.\n"
            "- Integracion sensor de gas: no es plug-and-play; requiere analisis de drivers. "
            "Unitree vende detector de gas propio.\n"
            "- Conectividad: validar cobertura de red en zona de patrullaje (puede necesitar almacenar "
            "localmente y sincronizar al recuperar senal).\n"
            "- Bateria: 2-4 horas segun manual. Debe volver solo a estacion de carga.\n"
            "Preguntas tecnicas a enviar a Vista: tipo de conectividad (fibra, WiFi, 4G/5G) en plantas "
            "y pozos; disponibilidad de energia electrica; velocidad de internet; tipo de camaras existentes.\n"
            "Estrategia: presentar el robot AL FINAL de la reunion (mayor interes de Vista, menor "
            "madurez del equipo). No comprometerse con fechas ni costos especificos.\n"
            "Vista parece querer el robot principalmente como marketing interno de la gerencia de "
            "innovacion ('sacar la foto' antes de fin de año).\n\n"
            "B. Videoanalytics (Camaras Inteligentes) — Madurez media\n"
            "Casos de uso:\n"
            "- Identificacion de derrames y fuego.\n"
            "- Alerta de intrusos y control de acceso.\n"
            "- Registro de EPP (casco, arnes, etc.).\n"
            "- Deteccion de actividades de riesgo (trabajo en altura sin arnes, persona bajo linea de fuego).\n"
            "- Camaras termograficas para puntos calientes en motores, cannerias, valvulas "
            "(analisis de mapa termico historico para detectar desviaciones).\n"
            "- Deteccion de fugas de gases con camaras infrarrojas especializadas.\n"
            "Capacidades confirmadas: identificacion de seguridad, reconocimiento facial, "
            "deteccion de derrames y fuego, analisis de imagenes y alertas.\n"
            "Incertidumbres: camaras termograficas (requiere investigacion); camaras IR para gas "
            "(no dominan el mercado). Precio camaras termicas: ~$600-700 USD.\n"
            "Estrategia: aprovechar primero infraestructura de camaras existente en Vista, "
            "luego incorporar nuevas tecnologias.\n\n"
            "C. Totem Interactivo (IA Conversacional) — Mayor madurez, presentar PRIMERO\n"
            "Casos de uso:\n"
            "- Security briefing en entrada de planta: alarmas activas, trabajos programados, simulacros.\n"
            "- Consultas sobre estado de instalacion: caudales, presiones, equipos.\n"
            "- Guia de procedimientos operativos paso a paso ante fallas.\n"
            "- Acceso a planos y diagramas de la instalacion.\n"
            "- Integracion con datos en tiempo real del cliente.\n"
            "Demo en vivo: Mariano puede cargar documentacion especifica para que el totem responda "
            "preguntas reales en la reunion. Gustavo y Sebastian pasaran a Mariano los temas.\n"
            "Precio referencia: totem basico desde $15.000-$20.000 USD (segun complejidad).\n\n"
            "3. Estrategia General para la Reunion con Vista\n"
            "Orden de presentacion: (1) Corporativo Acciona + Flock, (2) Totem, (3) Videoanalytics, (4) Robot.\n"
            "Marca: ir con Acciona como marca principal; Flock como 'Made by Flock' o 'Powered by Flock' "
            "(unidad de innovacion tecnologica de Acciona). Federico envia template Acciona.\n"
            "Costos: para Vista no dar numeros finos, si un orden de magnitud. Para funcionalidades "
            "genericas del robot, Flock puede absorber el costo; para desarrollos muy especificos, "
            "compartir costos con Vista.\n\n"
            "4. Situacion Big Dipper (Proveedor Robot Unitree)\n"
            "Big Dipper envio por error robot de mayor gama. Pablo gestiona reemplazo.\n"
            "Big Dipper participara como sponsor bronce en la feria Langaz (Oil & Gas Argentina, "
            "del 8 al 11 del mes siguiente, en Buenos Aires). Se evalua contactar a Big Dipper "
            "en la feria para establecer vinculo comercial como integradores.\n"
            "Plus Petrol ya tiene robots funcionando en Peru, haciendo POC en Argentina con "
            "proveedor desconocido — el equipo quiere averiguar mas.\n\n"
            "5. Feria Langaz (Oil & Gas Argentina)\n"
            "La expo mas grande de Oil & Gas en Argentina. Este año en Buenos Aires (normalmente en Neuquen). "
            "Participa toda la industria: Vista, YPF, Chevron, Tech Petrol, Plus Petrol. "
            "Equipo planea asistir preferentemente el miercoles.\n\n"
            "Accionables:\n"
            "- [Mariano + Gustavo/Sebastian] Redactar y enviar preguntas tecnicas a Vista por mail.\n"
            "- [Mariano] Preparar demo del Totem con informacion real para la reunion con Vista.\n"
            "- [Equipo tecnico] Avanzar en exploracion del ROS con el robot.\n"
            "- [Pablo + Federico/Diego] Gestionar relacion con Big Dipper para la feria Langaz.\n"
            "- [Gustavo/Sebastian] Armar presentacion formato Acciona; pasar a Federico → marketing/diseno.\n"
            "- [Todo el equipo] Reunion de seguimiento el jueves (media hora).\n"
            "- [Gustavo/Sebastian] Definir si postergar reunion Vista para mandar preguntas tecnicas primero."
        ),
    },
    {
        "source_id": "329520793",
        "date": "2025-06-17",
        "title": "Reunion PRAIA — Nombre del producto, avatar, B-Summit y modelo comercial",
        "content": (
            "Meeting: Reunion PRAIA — Nombre del producto, avatar, B-Summit y modelo comercial\n"
            "Date: 2025-06-17\n"
            "Participants: Federico Valentino Lacoste, Mariano (Penta), Mariano Ortega (Flock/CTO)\n\n"
            "Contexto: Reunion de definicion del producto de totems conversacionales con IA. "
            "Mariano se va de vacaciones en dos semanas; hay urgencia de cerrar definiciones clave "
            "antes del evento B-Summit.\n\n"
            "1. Nombre del Producto — Decision: PRAIA\n"
            "Opciones evaluadas:\n"
            "- XPI: acronimo de 'Experience meets Artificial Intelligence'.\n"
            "- PRAIA: derivado de XPI, evoca dualidad (humano + AI), claim 'Human Experience Powered by AI'.\n"
            "- Smile2AI: juega con sonrisa, numero 2 y AI.\n"
            "Todos los dominios disponibles en .com y .ai. Decision: PRAIA.\n"
            "Dominio: praia.com (se descarto .ai por redundancia, .io por costo $89 vs $20).\n"
            "Registro en DonWeb (incluye hosting y casillas @praia.com).\n"
            "El equipo de diseno ya trabajo sobre PRAIA, hay tiempo ganado.\n\n"
            "2. Logotipo\n"
            "Mariano tiene bocetos rapidos para los 3 nombres. Con PRAIA confirmado, se generaran "
            "4-5 opciones de logo para seleccion.\n\n"
            "3. Documento de Compromiso Entre Partes\n"
            "Federico subio template con clausula de confidencialidad. Mariano lo revisa y cierra.\n\n"
            "4. Modelo Comercial — Postergado\n"
            "Mati (comercial) esta de viaje. Se pospone hasta su regreso.\n"
            "Escenarios de monetizacion mapeados:\n"
            "- Alquiler o venta de totems para retail.\n"
            "- Alquiler para eventos/expos (una empresa pide totem para su stand en expo John Deere).\n"
            "- Modelo de trabajo a resultado (leads generados por el sistema).\n"
            "- Publicidad externa en el totem durante la interaccion.\n\n"
            "5. Casos de Uso del Sistema de Totems\n"
            "Presentacion con multiples casos de uso:\n"
            "- Retail/supermercados: 'El pastelero en casa' patrocinado por Aguila en seccion pasteleria.\n"
            "- Hospitales: atencion a personas con discapacidad.\n"
            "- Educacion/experiencial: concepto 'Liberidad' (biblioteca experiencial).\n"
            "- Banca y seguros: Banco Nacion, Nacion Seguros (proyecto vigente).\n"
            "- Museos: guias explicativos, pantallas inmersivas.\n"
            "- Ferias y eventos: orientacion, informacion de stands.\n"
            "- Ninos/bibliotecas: avatar de abuela que cuenta cuentos del libro que el nino apoya en el totem.\n"
            "- Cosmetica y moda.\n"
            "Un reel con todos estos casos correria en loop en el stand del B-Summit.\n\n"
            "6. Pagina Web y Landing\n"
            "Diseno esperado en dos semanas. Landing debe incluir: casos de uso, interfaz en accion, "
            "dinamica de conversacion visible. Mariano Ortega la codea cuando vuelva de vacaciones.\n"
            "Las tres prioridades: landing, presentacion comercial, y segundo caso de uso.\n\n"
            "7. Evento B-Summit — Logistica\n"
            "Federico coordina con Ignacio (organizador) para recibir plano del salon y elegir stand "
            "con buena ubicacion. Venue posible: Sheraton.\n"
            "Idea innovadora: colocar un segundo totem cerca de la entrada del evento como totem "
            "del B-Summit (guia a asistentes, informa charlas/expositores). Logo del B-Summit y "
            "'Powered by PRAIA' — funciona como publicidad y vitrina del producto.\n\n"
            "8. Conectividad para el Evento\n"
            "Sistema requiere internet (Simly + Eleven Labs son servicios online).\n"
            "Opciones: proveedor de internet del venue vs. Starlink propio.\n"
            "Plan de contingencia: mensaje predeterminado del avatar avisando que no tiene conexion.\n"
            "Alternativa: video filmado de sesion previa como plan B.\n"
            "Logistica: microfono corbatero para evitar loops de audio. Parlante de pie propio "
            "para el audio del totem, independiente del sistema de sonido del venue.\n\n"
            "9. Avatares del Sistema\n"
            "- Avatar para presentacion comercial en escenario: Simly + Eleven Labs (mejor calidad "
            "conversacional). Avatar ya desarrollado por Mari; la voz la hizo Mariano Ortega. "
            "Nombre sugerido: 'Milton' o 'Joao' (tono brasilero en linea con PRAIA).\n"
            "- Avatar para caso de uso demostrativo: Soul Machines (soulmachines.com). "
            "Trial de 7 dias vencido; cuesta $100/mes.\n\n"
            "10. Investigacion Tecnica — Emocionalidad en Voz\n"
            "Mariano Ortega investiga como generar emocionalidad en la voz del avatar a partir del "
            "texto del LLM. Problema: los modelos de voz leen literalmente el texto incluyendo "
            "indicaciones como 'dijo enojado'. Explorando uso de signos de exclamacion y recursos "
            "para modular el tono.\n\n"
            "11. Presentacion en Escenario — B-Summit\n"
            "Mariano tiene media hora en escenario del B-Summit.\n"
            "Concepto: storytelling inicial referenciando un evento real del pasado, luego 'destapa' "
            "el totem e interactua en vivo. Preguntas del publico orientadas por el speaker.\n"
            "Posibilidad de proyectar pantalla del totem en pantalla grande via HDMI.\n\n"
            "12. Segundo Cliente para el Totem\n"
            "Federico tiene contacto en concesionario Yondir (colaboracion previa en hackathon de RV). "
            "Se da plazo de 3 dias para confirmar si aporta el segundo caso de uso. Si no, se avanza "
            "con el plan B (totem del B-Summit).\n\n"
            "13. Community Management y Redes\n"
            "Mariano propone sumar la agencia de comunicacion de Flock. Se discute crear perfil de "
            "LinkedIn para PRAIA con contenido previo al evento. Flock tiene dos agencias: una de "
            "marca empleadora y una nueva orientada a ventas/contenido. Fede se asigna la tarea.\n\n"
            "Accionables:\n"
            "- [Mariano] Registrar dominio praia.com en DonWeb; coordinar logo con diseno.\n"
            "- [Mariano] Revisar y cerrar documento de compromiso.\n"
            "- [Federico] Contactar al concesionario Yondir; confirmar esta semana.\n"
            "- [Federico] Hablar con Ignacio (B-Summit) para plano del salon.\n"
            "- [Federico] Evaluar suma de agencia para community management de PRAIA.\n"
            "- [Mariano Ortega] Integrar avatar de Mari a Simly + Eleven Labs.\n"
            "- [Fede + Mariano] Definir guion y storytelling para presentacion en escenario.\n"
            "- [Todos] Definir nombre del avatar (propuestas: Milton, Joao).\n"
            "- [Mariano Ortega] Continuar investigacion de emocionalidad en voz.\n"
            "- [Equipo] Visitar venue (Sheraton) para evaluar logistica."
        ),
    },
    {
        "source_id": "312484523",
        "date": "2025-05-28",
        "title": "Alineacion desarrollo PRAIA — Dos totems para evento, Claro y landing",
        "content": (
            "Meeting: Alineacion desarrollo PRAIA — Dos totems para evento, Claro y landing\n"
            "Date: 2025-05-28\n"
            "Participants: Mariano Ortega, Marilyn Botheatoz, Mariano (Penta), Federico Valentino Lacoste, "
            "Federico (otro)\n\n"
            "Contexto: Reunion de alineacion tecnica y comercial entre el equipo de Flock (Mariano Ortega, "
            "Marilyn) y el equipo de Penta (Mariano, Federico) para avanzar en el desarrollo de PRAIA. "
            "Se validan expectativas de tiempos y tareas para la fecha del evento (B-Summit).\n\n"
            "1. Scope de Desarrollo\n"
            "Tres tareas principales acordadas:\n"
            "- Totem 1: 'vendedor de totems' para el escenario y stand del B-Summit (mas simple, "
            "basado en RAG sobre documento que ya tiene Fede).\n"
            "- Totem 2: totem para Claro (u otro cliente) para el stand.\n"
            "- Landing del producto PRAIA.\n\n"
            "2. Personalidad del Totem Vendedor de Totems\n"
            "Discusion sobre que personalidad setear. Consenso:\n"
            "- Experto en el universo de Flock Y en el universo de Penta (trade/retail).\n"
            "- Que entienda tecnicismos de marketing/trade (ej. 'Pass to Purchase' en sentido de "
            "trade marketing, no como camino de compra literal).\n"
            "- Lenguaje accesible y sencillo, sin palabras tecnicas exageradas.\n"
            "- Que transmita el valor del servicio combinado de ambas empresas.\n"
            "Plan: armar prompt inicial → pasarlo a Penta para que jueguen → iterar con feedback → "
            "agregar informacion faltante (papers, libros de marketing que compartan).\n\n"
            "3. Storytelling para la Presentacion en Escenario\n"
            "Una persona interactua con el totem en escenario (no el publico directamente, por riesgos "
            "tecnicos: microfono, interpretacion erronea de IA, fallos).\n"
            "El publico puede hacer preguntas al speaker, quien las transmite al totem.\n"
            "En el stand si habra interaccion directa uno a uno del publico con el totem (mas abierta).\n"
            "Guion preestablecido para quien presente en escenario, que muestre atributos clave:\n"
            "- Cambio de idioma (simple de implementar).\n"
            "- Reconocimiento facial (posible, pero no implementar para este deadline).\n"
            "- Lenguaje de senyas (complejo: requiere modelo distinto y animacion; mencionar como "
            "capacidad posible).\n"
            "- Metamorfosis del avatar: puede ser cualquier personaje para cualquier cliente "
            "(Jumbo, Claro, Roemers, etc.).\n"
            "- Humor y personalidad: el guion puede incluir chistes o momentos planificados.\n\n"
            "4. Avatar — Decision de Diseno\n"
            "Discusion sobre si usar avatar tipo 'Cassandra' (hiperrealista, da efecto 'creepy'), "
            "algo abstracto/geometrico, o algo intermedio (como el de aeropuertos).\n"
            "Marilyn: el tiempo es condicionante. Crear algo nuevo abstracto no es viable en el "
            "plazo actual. Dos opciones viables:\n"
            "- A: avatar similar al de aeropuertos con otra identidad (mismo stack Simly, "
            "iterable rapidamente).\n"
            "- B: esfera con animaciones (no humano, pero hace claro que es IA; se puede explorar "
            "en el tiempo disponible, pero menos 'shock value').\n"
            "Decision: avanzar con avatar (opcion A). Si encuentran algo mejor ya como producto, "
            "lo proponen y deciden entre todos.\n"
            "Ver catalogo de avatares de Simly → Marilyn lo muestra a los clientes.\n\n"
            "5. Segundo Totem — Claro\n"
            "Federico tiene contacto en Claro (encargado de todos los centros de atencion al cliente).\n"
            "No hay requerimientos cerrados aun; Federico envio lista de requisitos a Claro y esperaba "
            "respuesta. El contacto de Claro expreso preocupacion por 'reemplazar asesores' → "
            "Federico lo llevo a que el sistema potencia al asesor, no lo reemplaza.\n"
            "Vision de Federico: totem que detecte perfil del cliente y sugiera upselling al asesor "
            "(ej: cliente fanático de audiolibros → recomendar auriculares nuevos).\n"
            "Estrategia tecnica: no depender de APIs de Claro → que Claro de el contenido (catalogo, "
            "abonos, equipos) y Flock lo mete directo como conocimiento.\n"
            "Si Claro no puede compartir info: buscar otro cliente u otra vuelta.\n"
            "Federico sumara a Mariano Ortega si la reunion con Claro va a nivel tecnico.\n\n"
            "6. Landing\n"
            "Mariano (Penta) tiene reunion de diseno hoy para avanzar en la landing. Tiempo TBD.\n\n"
            "7. Hardware del Stand\n"
            "En el stand: dos totems + una pantalla.\n"
            "Totem para Nacion Seguros ya armado (ese cliente mostro interes en el sistema).\n"
            "Idea: aprovechar y armar 2 totems mas para el evento → quedan como capital fisico.\n"
            "Recomendacion de hardware que pasara Flock: componentes de computadora para el hardware "
            "interno del totem. Agregar camara (aunque no se use para reconocimiento facial en esta "
            "instancia; en muy poco tiempo sera necesario).\n"
            "Importante: hacer el totem lo mas facil de transportar posible (cabe en el bau del auto) "
            "para visitas a clientes. Diseno desarmable: mitad superior + mitad inferior.\n\n"
            "8. Conectividad en Evento\n"
            "El sistema requiere internet (Simly + Eleven Labs son online).\n"
            "Marilyn: contemplar auriculares para comunicacion uno a uno con el totem en ambiente ruidoso. "
            "Microfono corbatero para presentacion en escenario. Parlante de pie propio para el audio del "
            "totem (independiente del sistema de sonido del venue).\n"
            "Conectividad del venue a validar con el organizador del evento.\n\n"
            "9. Marilyn Se Suma al Proyecto\n"
            "Marilyn Botheatoz se incorpora formalmente al grupo de trabajo de PRAIA para acompañar "
            "el proyecto y no depender de Mariano Ortega para actualizaciones.\n\n"
            "Accionables:\n"
            "- [Mariano Ortega/Marilyn] Arrancar con el Totem 1 (vendedor de totems) y hacerlo disponible.\n"
            "- [Marilyn] Mostrar catalogo de avatares de Simly al cliente.\n"
            "- [Federico] Conseguir requerimientos de Claro esta semana.\n"
            "- [Mariano (Penta)] Avanzar en landing (reunion de diseno hoy).\n"
            "- [Federico] Validar conectividad y logistica tecnica del venue con el organizador.\n"
            "- [Mariano Ortega] Pasar recomendacion de hardware para los totems.\n"
            "- [Equipo] Definir storytelling y guion para presentacion en escenario.\n"
            "- [Marilyn] Agregar al grupo de WhatsApp de PRAIA."
        ),
    },
]


async def main() -> None:
    settings = get_settings()
    session_factory = get_session_factory()
    pipeline = IngestionPipeline(embedder=Embedder(api_key=settings.openai_api_key))

    async with session_factory() as db:
        for t in TRANSCRIPTS:
            print(f"Ingesting {t['source_id']} — {t['title']}...")
            result = await pipeline.ingest_raw(
                db=db,
                user_id=USER_ID,
                content=t["content"],
                source="fathom",
                source_id=t["source_id"],
                metadata={
                    "title": t["title"],
                    "date": t["date"],
                    "recording_url": f"https://fathom.video/calls/{t['source_id']}",
                },
            )
            print(f"  -> created={result.documents_created} updated={result.documents_updated}")
        await db.commit()

    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
